#!/bin/python3

import sys
#https://www.programiz.com/python-programming/iterator

class PowTwo:
    """Class to implement an iterator of powers of two"""

    def __init__(self, max = 0):
        self.max = max

    def __iter__(self):
        self.n = 0
        return self

    def __next__(self):
        if self.n <= self.max:
            result = 2 ** self.n
            self.n += 1
            return result
        else:
            raise StopIteration
	    
def main(argv):
	
	p = PowTwo(20)
	
	for i in p:
		print(i)
	
if __name__ == "__main__":main(sys.argv[0:])
