#!/bin/python3

import sys

def main(argv):
	
	integer = 314
	
	#intToStr(integer)
	
	print(str(strToInt("1234")))

def strToInt(inp):
	
	is_negative = False
	
	len_inp = len(inp)
	
	if len_inp<0:
		raise ValueError("Invalid")
	
	start_at_index = 0
	
	if inp[0] == "-":
		is_negative = True 
		start_at_index = 1
		
	if inp[0] == "+":
		start_at_index = 1	
	
	if len_inp > start_at_index:
		 
		running_total = 0
		
		for c in inp[start_at_index:len_inp]:
			running_total = running_total*10 + int(c)
			print(str(running_total), int(c))		
		return 	running_total
	
	return 0

	
def intToStr(integer):

	is_negative = False
	
	if integer<0:
		is_negative = True
		
	if integer==0:	
		return "0"
	
	s = []
	
	while integer!=0:
		
		last_dig      = integer % 10
		integer	      = integer //10
		
		s.append(chr(ord('0') + last_dig))
		
	print("FINAL STR:" + ''.join(reversed(s)))	
	
	
		
if __name__ == "__main__":main(sys.argv[0:])
